apiVersion: v2
name: kube-prometheus-wrapper
description: Wrapper chart for kube-prometheus-stack
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: kube-prometheus-stack
    version: "65.2.0"   # pick the version you want
    repository: "https://prometheus-community.github.io/helm-charts"

